"use client";
import { useState } from "react";
import { Sparkles, Mail, Brain, MessagesSquare, Loader2, Copy } from "lucide-react";
import { toast } from "sonner";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

type Helper = "cover-letter" | "skill-gap" | "interview-prep";

export function AIHelpers({ jobId, hasResume }: { jobId: string; hasResume: boolean }) {
  if (!hasResume) {
    return (
      <Card>
        <CardContent className="py-6 text-center text-sm text-[var(--color-fg-muted)]">
          Set an active resume to use AI helpers.
        </CardContent>
      </Card>
    );
  }
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-base">
          <Sparkles className="h-4 w-4 text-[var(--color-accent)]" /> AI helpers
        </CardTitle>
      </CardHeader>
      <CardContent className="grid gap-2 sm:grid-cols-3">
        <HelperButton kind="cover-letter" label="Cover letter" Icon={Mail} jobId={jobId} />
        <HelperButton kind="skill-gap" label="Skill gap" Icon={Brain} jobId={jobId} />
        <HelperButton kind="interview-prep" label="Interview prep" Icon={MessagesSquare} jobId={jobId} />
      </CardContent>
    </Card>
  );
}

function HelperButton({
  kind,
  label,
  Icon,
  jobId,
}: {
  kind: Helper;
  label: string;
  Icon: React.ComponentType<{ className?: string }>;
  jobId: string;
}) {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [output, setOutput] = useState<string>("");

  async function run() {
    setLoading(true);
    setOutput("");
    try {
      const r = await fetch(`/api/ai/${kind}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ jobId }),
      });
      if (!r.ok) {
        const j = await r.json().catch(() => ({}));
        throw new Error(j?.error?.message || `HTTP ${r.status}`);
      }
      if (kind === "cover-letter") {
        const reader = r.body?.getReader();
        const dec = new TextDecoder();
        if (reader) {
          let buf = "";
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            buf += dec.decode(value, { stream: true });
            setOutput(buf);
          }
        }
      } else {
        const j = (await r.json()) as { ok: boolean; data?: string };
        setOutput(j.data ?? "");
      }
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "AI request failed");
    } finally {
      setLoading(false);
    }
  }

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        setOpen(o);
        if (o && !output) run();
      }}
    >
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="justify-start">
          <Icon className="h-4 w-4" /> {label}
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>{label}</DialogTitle>
          <DialogDescription>Generated by Gemini · stripped of PII before send.</DialogDescription>
        </DialogHeader>
        <div className="max-h-[60vh] overflow-y-auto whitespace-pre-wrap rounded-md border border-[var(--color-border)] bg-[var(--color-bg-subtle)] p-4 text-sm leading-relaxed">
          {loading && !output ? (
            <span className="inline-flex items-center gap-2 text-[var(--color-fg-muted)]">
              <Loader2 className="h-4 w-4 animate-spin" /> Thinking...
            </span>
          ) : (
            output || "—"
          )}
        </div>
        <div className="flex justify-end gap-2">
          <Button
            variant="outline"
            size="sm"
            disabled={!output}
            onClick={() => {
              navigator.clipboard.writeText(output);
              toast.success("Copied");
            }}
          >
            <Copy className="h-4 w-4" /> Copy
          </Button>
          <Button variant="ghost" size="sm" onClick={() => run()} disabled={loading}>
            {loading && <Loader2 className="h-4 w-4 animate-spin" />} Regenerate
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
